spring:
  datasource:
    url: jdbc:mysql://localhost:3306/est?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ok
mybatis:
  mapper-locations: classpath:mapper/*.xml